#!/usr/bin/env python
import numpy as np
import math
import matplotlib.pyplot as plt

import rospy
import geometry_msgs.msg
import actionlib
from   move_base_msgs.msg import MoveBaseAction, MoveBaseGoal
import tf

class RobotPolygonPath():

    def __init__(self):

        rospy.init_node('move_base_waypoints')
        num_sides = rospy.get_param('robot_polygon_path/num_sides')
        side_length = rospy.get_param('robot_polygon_path/side_length')

        listener = tf.TransformListener()
        self.pose = self.get_2d_pose(listener)
        self.waypoints = self.plan_waypoints(num_sides, side_length, self.pose)
        self.goal_cnt = 0

        #Create action client
        self.client = actionlib.SimpleActionClient('move_base',MoveBaseAction)
        rospy.loginfo("Waiting for action server...")
        wait = self.client.wait_for_server(rospy.Duration(5.0))
        if not wait:
            rospy.logerr("Action server not available!")
            rospy.signal_shutdown("Action server not available!")
            return
        rospy.loginfo("Connected to server")
        rospy.loginfo("Starting goal traversal...")
        self.run()

    def plan_waypoints(self, num_sides, side_length, pose=[0, 0, 0]):
        """
        Returns a list of 2D poses that form an equilateral polygon
        """
        waypoints = np.full((num_sides, 3), pose, dtype=float)

        # Normalize given yaw
        angle_norm = pose[2] % (2 * np.pi)

        # Find bearing (angle delta at each turn)
        bearing = 2 * np.pi / num_sides

        coord = np.array(pose)
        for i in range(0, num_sides - 1):
            waypoints[i][0] = math.cos(angle_norm) * side_length + coord[0]
            waypoints[i][1] = math.sin(angle_norm) * side_length + coord[1]
            waypoints[i][2] = (angle_norm + bearing) % (2 * np.pi)
            angle_norm = waypoints[i][2]

            coord = waypoints[i]

        return waypoints

    def draw_path(self, waypoints, pose):
        x = [pose[0]]
        y = [pose[1]]
        for pt in waypoints:
            x.append(pt[0])
            y.append(pt[1])

        plt.plot(x, y)
        plt.axis('scaled')
        plt.show()


    def get_2d_pose(self, listener):
        try:
            listener.waitForTransform("/map", "/base_link", rospy.Time(0), rospy.Duration(3.0))
            (trans, rot) = listener.lookupTransform('/map', '/base_link', rospy.Time(0))
            euler = tf.transformations.euler_from_quaternion(rot)
            yaw = euler[2]
            return [trans[0], trans[1], yaw]
        except (tf.LookupException, tf.ConnectivityException, tf.ExtrapolationException):
            rospy.signal_shutdown("Unable to retrieve pose")

    def active(self):
        rospy.loginfo("Goal pose "+str(self.goal_cnt+1)+" is now being processed by the Action Server...")

    def feedback(self, feedback):
        rospy.loginfo("Feedback for goal pose "+str(self.goal_cnt+1)+" received")

    def done(self, status, result):
        self.goal_cnt += 1
        if status == 2:
            rospy.loginfo("Goal pose "+str(self.goal_cnt)+" received a cancel request after it started executing, completed execution!")

        if status == 3:
            rospy.loginfo("Goal pose "+str(self.goal_cnt)+" reached") 
            if self.goal_cnt < len(self.waypoints):
                next_goal = MoveBaseGoal()
                next_goal.target_pose.header.frame_id = "map"
                next_goal.target_pose.header.stamp = rospy.Time.now()

                next_goal.target_pose.pose.position.x = self.waypoints[self.goal_cnt][0] 
                next_goal.target_pose.pose.position.y = self.waypoints[self.goal_cnt][1] 

                # to send orientation with a yaw we need quaternion transform
                x, y, z, w = tf.transformations.quaternion_from_euler(0, 0, self.waypoints[self.goal_cnt][2])
                next_goal.target_pose.pose.orientation.x = x
                next_goal.target_pose.pose.orientation.y = y
                next_goal.target_pose.pose.orientation.z = z
                next_goal.target_pose.pose.orientation.w = w

                rospy.loginfo("Sending goal pose "+str(self.goal_cnt+1)+" to Action Server")
                rospy.loginfo(str(self.waypoints[self.goal_cnt]))
                self.client.send_goal(next_goal, self.done, self.active, self.feedback) 
            else:
                rospy.loginfo("Final goal pose reached!")
                rospy.signal_shutdown("Final goal pose reached!")
                return

        if status == 4:
            rospy.loginfo("Goal pose "+str(self.goal_cnt)+" was aborted by the Action Server")
            rospy.signal_shutdown("Goal pose "+str(self.goal_cnt)+" aborted, shutting down")
            return

        if status == 5:
            rospy.loginfo("Goal pose "+str(self.goal_cnt)+" has been rejected by the Action Server")
            rospy.signal_shutdown("Goal pose "+str(self.goal_cnt)+" rejected, shutting down")
            return

        if status == 8:
            rospy.loginfo("Goal pose "+str(self.goal_cnt)+" received a cancel request before it started executing, successfully cancelled")


    def run(self):
        goal = MoveBaseGoal()
        goal.target_pose.header.frame_id = "map"
        goal.target_pose.header.stamp = rospy.Time.now() 
        
        goal.target_pose.pose.position.x = self.waypoints[self.goal_cnt][0] 
        goal.target_pose.pose.position.y = self.waypoints[self.goal_cnt][1] 

    	# to send orientation with a yaw we need quaternion transform
        x, y, z, w = tf.transformations.quaternion_from_euler(0, 0, self.waypoints[self.goal_cnt][2])
        goal.target_pose.pose.orientation.x = x
        goal.target_pose.pose.orientation.y = y
        goal.target_pose.pose.orientation.z = z
        goal.target_pose.pose.orientation.w = w
        
        rospy.loginfo("Sending goal pose "+str(self.goal_cnt+1)+" to Action Server")
        rospy.loginfo(str(self.waypoints[self.goal_cnt]))
        self.client.send_goal(goal, self.done, self.active, self.feedback)
        rospy.spin()

if __name__ == "__main__":
    robot = None
    try:
        robot = RobotPolygonPath()
    except rospy.ROSInterruptException:
        rospy.loginfo("Navigation finished.")
    finally:
        robot.draw_path(robot.waypoints, robot.pose)
